### ISSUE TITLE
90 numbers

### ISSUE THREAD

**Issue by Manumaier** [karolbrennan/letsplaybingo#27]
Hello, my english is not the best, i hope u Unterstand me. We Stream since Corona every Friday Bingo with Friends privatly. Its Not for commercial. Every Player spends one time the win. But we Need 90 Numbers - is it possible? This Version is very beautyful, Good Job! Have a nice Day Manu

**Comment by karolbrennan** [comment]
@Manumaier 90 ball bingo has been released! https://90ball.letsplaybingo.io - please let me know what you think!
