### ISSUE TITLE
With no caller voice selected, site acts weird

### ISSUE THREAD

**Issue by m2pt5** [karolbrennan/letsplaybingo#57]
It shows multiple numbers at once on the board as having been drawn, but they don't appear in the history. Selecting a caller voice returns behavior to normal.

**Comment by karolbrennan** [comment]
Oh that's super weird! Thanks for reporting I'll look into it!

**Comment by karolbrennan** [comment]
Fixed this by assigning a caller on load if one hasn't been selected. Utilizing the browser's language to choose the first available caller with that language.
