### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by chrisls121** [karolbrennan/letsplaybingo#9]
Hi Karol,

Very nice and clean design you have for your bingo board, I was hoping to use some of this code as a basis for an online bingo game. I don't see a licence posted in the repo, when you get a chance could you update the repo with a licence?

Thanks,
Chris

**Comment by karolbrennan** [comment]
Hey @chrisls121 I'm so sorry, I didn't see this until just now. Thank you for the compliments on my app. I have just added an MIT license, so please feel free to use it. I'd love to see what you do with it!

**Comment by chrisls121** [comment]
No worries, I appreciate the license change, the project got put on hold but I will definitely let you know if we end up using it.
